config/routes.rb
Rails.application.routes.draw do
  resources :tasks, only: [:index, :show] do
    resources :completed_tasks, only: [:create, :destroy]
  end

  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }

  root "tasks#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completed_task.rb
class CompletedTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
  validates :task_id, :uniqueness => { :scope => :user_id }
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :completed_tasks
  has_many :users, through: :completed_tasks
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :completed_tasks
  has_many :tasks, through: :completed_tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/completed_tasks_controller.rb
class CompletedTasksController < ApplicationController
  before_action :authenticate_user!

  def create
    @task = Task.find(params[:task_id])
    @completed_task = CompletedTask.create(task: @task, user: current_user, completed: true)

    if @completed_task
      redirect_to tasks_path, notice: 'Tarea completada con éxito.'
    else
      redirect_to tasks_path, alert: 'La tarea no ha podido ser completada.'
    end
  end

  def destroy
    @task = Task.find(params[:task_id])
    @completed_task = CompletedTask.find_by(task: @task, user: current_user, completed: true)

    if CompletedTask.exists?(user_id: current_user.id, task_id: @task.id , completed: true)
      @completed_task.destroy
      redirect_to tasks_path, alert: 'La tarea ya no se encuentra completada.'
    else
      redirect_to tasks_path, alert: 'La tarea no ha sido completada aun.'
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
    @top_five = CompletedTask.all.where(task_id: @task).order(:created_at).limit(5).pluck('user_id')
    @completed_task_users_id = CompletedTask.all.where(task_id: @task).pluck('user_id')
  end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/completed_tasks_helper.rb
module CompletedTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">Bucket list del 18°</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="#">Completados <%= CompletedTask.where(user_id: current_user.id, completed: true).count %> / <%= Task.all.count %><span class="sr-only">(current)</span></a>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <% if user_signed_in? %>
          <%= link_to "Salir", destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <% else %>
          <a class="nav-link" href="<%= new_user_session_path %>">Iniciar Sesión<span class="sr-only">(current)</span></a>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bucketlist18</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container my-3">
      <%= yield %>
    </div>

    <footer class="bg-dark mt-5 py-3">
      <p class="text-center text-white">Prueba semana N°19, Fullstack G20, Desafío Latam. Creado por Javier.</p>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/index.html.erb
<div class="card-columns">
  <% @tasks.each do |task| %>
    <div class="card">
      <% if user_signed_in? %>
        <% if  current_user.completed_tasks.find_by(task_id: task.id) %>
          <%= image_tag task.photo, class: "card-img-top" %>
        <% else %>
          <%= image_tag task.photo, class: "card-img-top filtered" %>
        <% end %>
        <% else %>
          <%= image_tag task.photo, class: "card-img-top" %>
      <% end %>
      <div class="card-body">
        <h5 class="card-title">
          <%= link_to task.name, task_path(task.id), class:'text-dark' %>
        </h5>
        <% if user_signed_in? %>
          <% if  current_user.completed_tasks.find_by(task_id: task.id) %>
            <small class="text-muted">Last updated
              <%= time_ago_in_words(current_user.completed_tasks.find_by(task_id: task.id).updated_at)%>
              ago</small>
          <% else %>
            <small class="text-muted">Not completed yet.</small>
          <% end %>
        <% end %>
        <br>
        <div class="mt-3">
          <% if user_signed_in? %>
            <% if  current_user.completed_tasks.find_by(task_id: task.id) %>
              <%= link_to "NO Listo",
                  task_completed_task_path(task, current_user),
                  method: :delete , class: 'btn btn-danger'
              %>
            <% else %>
              <%= link_to "Listo", task_completed_tasks_path(task),
                  method: :post,
                  class: 'btn btn-primary'
              %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-4">
    <div class="card">
      <%= image_tag @task.photo, class: "card-img-top" %>
      <div class="card-body">
        <h5 class="card-title"><%= @task.name %></h5>
        <p class="card-text"><%= @task.description %></p>
      </div>
    </div>
  </div>
  <div class="col-4">
    <table class="table">
      <thead>
        <tr>
          <th>Los primeros 5 que completaron la tarea</th>
        </tr>
      </thead>
      <tbody>
        <% @top_five.each do |u|%>
          <tr class="row">
            <td class="col-3"><%= User.find(u).photo ? image_tag(User.find(u).photo, :class => "img-fluid") : image_tag("https://image.flaticon.com/icons/png/512/97/97895.png", :class => "img-fluid")%></td>
            <td class="col"><%= User.find(u).name ? User.find(u).name : "-"%></td>
            <td><%= User.find(u).email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-4">
    <table class="table">
      <thead>
        <tr>
          <th>Quienes han completado esta tarea</th>
        </tr>
      </thead>
      <tbody>
        <% @completed_task_users_id.each do |u|%>
          <tr>
            <td><%= User.find(u).email %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>